docusaurus.config.js
With the docs being public, we can link each page to the corresponding file in the repo
- Adds the edit url to the docusaurus config
=> Enable edit link

code_blocks/getting-started/installation/kmp_8.ruby, docs/getting-started/installation/kotlin-multiplatform.mdx
We (@MarkVillacampa and myself) found a specific scenario in which iOS compilation might fail when integrating purchases-kmp. This was reported in https://github.com/RevenueCat/purchases-kmp/issues/275. 
Adds a `post_install` script workaround created by Mark, for when this compilation failure occurs.
=> Adds a `post_install` script to the KMP docs to work around a possible compilation error

docs/welcome/projects/collaborators.md
This is related to the HackerOne report https://hackerone.com/reports/2916755 where the wording about the Administrator role is ambiguous because "any billing" can also mean customer billing data which the administrator does have access to.
=> Update ambiguous wording in administrator role

docs/offerings/offerings.md
A side-effect of the recent docs changes made it less obvious of how to fetch offerings. 
Reworks the introduction, and adds additional context to the new Offerings overview page, linking to paywalls, fetching offerings, and the API.
=> Improve offerings doc

openapi-spec/api-v1.yaml
Noticed expiration date was not marked as nullable in the OpenAPI v1.
We do say expiration date can be null for lifetime access entitlements in the `CustomerInfo` documentation, which is built from the get subscriber API endpoint:
https://github.com/RevenueCat/docs/blob/main/docs/customers/customer-info.mdx?plain=1#L291
=> [API v1] Make entitlement expiration date nullable

code_blocks/subscription-guidance/subscription-offers/ios-winback-offers-fetch-eligible-winback-offers-capacitor.ts, code_blocks/subscription-guidance/subscription-offers/ios-winback-offers-fetch-eligible-winback-offers-cordova.js, code_blocks/subscription-guidance/subscription-offers/ios-winback-offers-purchase-winback-offer-capacitor.ts, code_blocks/subscription-guidance/subscription-offers/ios-winback-offers-purchase-winback-offer-cordova.js, docs/subscription-guidance/subscription-offers/ios-subscription-offers.mdx
This PR introduces code blocks demonstrating how developers can display & redeem win-back offers on custom paywalls in Capacitor and Cordova
=> Add Cordova & Capacitor Code Blocks for Redeeming Win-Back Offers on Custom Paywalls

code_blocks/customers/user-ids_16.cs, code_blocks/migrating-to-revenuecat/observer-mode_6.cs, docs/migrating-to-revenuecat/sdk-or-not/finishing-transactions.mdx
`.SetObserverMode()` was removed in the most recent major release of Unity. This PR updates references to it in the docs.
- Removed `.SetObserverMode()` reference in `code_blocks/customers/user-ids_16.cs` - observer mode isn't needed in the spots of the documentation that this is shown in
- Replaced `.SetObserverMode()` with `.SetPurchasesAreCompletedBy()` in `code_blocks/migrating-to-revenuecat/observer-mode_6.cs`
- Added a note instructing the user to specify which StoreKit version they're using when specifying that purchases will be completed by their app
=> Update .SetObserverMode calls in Unity

docs/customers/user-ids.mdx, docs/getting-started/configuring-sdk.mdx
Our current 'Identifying Customers' doc is ugly and has a lot of irrelevant information sprinkled throughout the 'normal' implementation flow 
Additionally, our 'Configuring SDK' doc needed some restructuring
- better organized toc, hide and push out some advanced topics
=> Improve customer identity & configuring SDK flow

docs/test-and-launch/sandbox/apple-app-store.mdx
In December 2024, Apple unexpectedly updated their TestFlight subscription renewal times. We wrote about this [here](https://www.revenuecat.com/blog/engineering/the-ultimate-guide-to-subscription-testing-on-ios/#h-subscription-renewal-rates-in-the-production-sandbox), but our docs hadn't yet been updated to reflect these changes.
=> Updated iOS TestFlight subscription renewal time blurb and table

docs/test-and-launch/sandbox/apple-app-store.mdx
Add Sandbox Apple Account creation steps for newer iOS version.
Found this solution [here](https://stackoverflow.com/a/79183072/875806). It says iOS 18.2. I'm on 18.2.1, and confirm this is correct now, but I do not know if it's true for 18.0.x or 18.1.x.
=> Add Sandbox Apple Account creation location for iOS 18

code_blocks/customers/customer-info_12.java
We now check whether the entitlement exists before accessing `.isActive()`.
```
if (customerInfo.getEntitlements().get(<your_entitlement_id>).isActive()) {
// user has access to "your_entitlement_id"
}
```
```
if (customerInfo.getEntitlements().get(<your_entitlement_id>) != null
&& customerInfo.getEntitlements().get(<your_entitlement_id>).isActive()) {
// user has access to "your_entitlement_id"
}
```
=> Fixed possible Nullpointexception when checking subscription status in Java

openapi-spec/api-v1.yaml
We added these two new properties to the transactions in the `CustomerInfo`
=> Add `display_name` and `price` to subscription and `non_subscription`

code_blocks/web/revenuecat-billing/redemption_flutter.dart, code_blocks/web/revenuecat-billing/redemption_react.ts, code_blocks/web/revenuecat-billing/redemption_unity.cs, docs/web/revenuecat-billing/redemption-links.mdx
This adds some instructions on how to use redemption links on the hybrids. Note that I haven't added specific instructions on how to obtain the deep link on each hybrid, since some of them might depend on the developer's implementation details. For now, I've just added links to the official deep link instructions on each of those.
This does not include KMP and Capacitor which still don't have support for redemption links.
=> Update redemption link instructions for current hybrid SDKs

src/css/custom.css, src/theme/Root.js
This allows documentation pages to be embedded within an iframe without navigation elements.
Adding `?embed=true` to the page turns this on.
A hook that swaps the styles based on that param. I used session storage for temporary persistence, so that clicking on links still works without resetting the embed mode setting.
References COFE-200
\-
=> Add support for embedded docs mode

package.json, src/plugins/tailwind/tailwind-config.cjs, yarn.lock
I added embedded docs styling in #616, but the production build didn't contain it because the CSS minimization step choked on the new syntax. 
This adds `postcss-preset-env` to fix it.
In the future, LightningCSS should negate the need for this tooling (as part of Docusaurus Faster https://github.com/facebook/docusaurus/issues/10556). I briefly tried turning it on instead, but there were a lot small errors that would need to be fixed.
COFE-200
N/A
=> Fix PostCSS minimization

docs/customers/trusted-entitlements.mdx
Trusted entitlements used to be disabled by default but it changed recently. The docs reflect that change but don't mentioned that if you are on an older version, it's disabled. See conversation [here](https://revenuecat.slack.com/archives/C030CB80FQ9/p1737988516485639).
=> Add info box about version availability

code_blocks/getting-started/installation/flutter_1.yaml, code_blocks/getting-started/installation/kmp_1.toml, docs/getting-started/installation/android.mdx, docs/getting-started/installation/capacitor.mdx, docs/getting-started/installation/flutter.mdx, docs/getting-started/installation/ios.mdx, docs/getting-started/installation/reactnative.mdx, docs/getting-started/installation/roku.mdx, docs/getting-started/installation/unity.mdx, docs/getting-started/installation/web-sdk.mdx, docs/tools/paywalls/installation.mdx
We had SDK versions listed in the paywall installation instructions. I added badges for all of our SDKs to show the latest versions, and updated the code snippets to not explicitly show old versions. They now show `"<latest version>"`, with the badge directly above it.
For example:
I also added badges to the "Installing the SDK" pages for each SDK, and removed an old warning for Android in paywalls.
=> Updated old paywall versions

docs/web/revenuecat-billing.mdx, docs/web/revenuecat-billing/product-setup.md
Bring back docs for accelerated sandbox in Web Billing. (jumped the gun merging).
=> Web Billing Accelerated Sandbox

docs/getting-started/installation/flutter.mdx, docs/test-and-launch/sandbox/google-play-store.mdx
It looks like Flutter projects may require the Android BILLING permission to initially upload the APK to Google. This unlocks product configuration in Google Play. I also added a similar callout to the Google Play Sandbox document.
=> Added Android billing permission callout in Flutter & Sandbox

docs/test-and-launch/debugging/troubleshooting-the-sdks.mdx
The "Troubleshooting SDKs" page does not list the SDKs that we list on the "Installing the SDK" docs page.
* Ensures missing SDKs are listed on the 'Troubleshooting SDKs' page. 
* Reorders to better match the order of SDKs listed on the "Installing the SDK."
NA
NA
=> Ensures missing SDKs are listed on the 'Troubleshooting SDKs' page. 

docs/platform-resources/server-notifications/google-server-notifications.md
This ticket demonstrates that server notifications can sometimes cause less than accurate pricing in Google: https://linear.app/revenuecat/issue/DENG-1096/google-play-transaction-discrepancy-rc-reporting-more-than-the-google#comment-db68abaa
We want to strongly advise developers to enable it for pricing accuracy too.
=> Add price accuracy to why Google Server Notifications should be enabled

docs/subscription-guidance/subscription-offers/ios-subscription-offers.mdx
We've re-tested the win-back message screen in sandbox and found that it doesn't appear to be flaky any longer, so this removes the flakiness warning
Remove warning about the win-back storekit message not appearing 100% of the time
=> Remove flaky sandbox win-back message testing warning

docs/getting-started/restoring-purchases.mdx
For some reason, the Obj-C code block under restoring purchases is named "Code" instead of "Objective-C". This fixes the issue by providing an explicit name for the code block.
Page link: https://www.revenuecat.com/docs/getting-started/restoring-purchases
=> correctly name objc code block

src/css/custom.css
The styling wasn't great for mobile devices for the empty offerings troubleshooting wizard
| Before | After |
|--------|-------|
| ![Before 2](https://github.com/user-attachments/assets/c217d966-5fab-4149-884f-3fdf3173b77d) | ![After 1](https://github.com/user-attachments/assets/ff414e11-18d5-4085-9f91-3dc5a967965e) |
| ![Before 1](https://github.com/user-attachments/assets/4b0fb279-83cb-41ca-9a36-31b9a3592862)  | ![After 2](https://github.com/user-attachments/assets/5186d83d-89e5-487c-8e50-941c6e046065) |
some styling changes for small screens
=> Improvements for the troubleshooting wizard on small screens

code_blocks/web/web-billing/redemption_capacitor.ts, code_blocks/web/web-billing/redemption_kmp.kt, docs/web/web-billing/redemption-links.mdx
We have just (are in the process of) releasing support for redemption links in KMP and Capacitor, the missing hybrids to support it. This updates the docs indicating this added support with some basic examples of API usage.
=> Add redemption links docs for missing hybrids

docs/tools/customer-center.mdx, docs/tools/customer-center/customer-center-flutter.mdx, docs/tools/customer-center/customer-center-installation.mdx, docs/tools/customer-center/customer-center-react-native.mdx, sidebars.js, src/components/CustomerCenter/CustomerCenterSDKTable.tsx
Add basic docs for flutter and RN
- Flutter page
- RN page
- Support SDK component
=> feat: Add CustomerCenter for flutter and RN

docs/platform-resources/server-notifications/apple-server-notifications.mdx
The 'User Identity' section of the Apple Server Notifications doc was a bit unclear, and did not mention that we don't set the `appAccountToken` in StoreKit 2 when the App User Id is not a valid UUID.
New text:
> ### User identity
> 
> New purchases are associated with the [App User ID](/customers/identifying-customers/) that matches the [`appAccountToken`](https://developer.apple.com/documentation/appstoreserverapi/appaccounttoken) field of the transaction. If you are using RevenueCat's SDK to track purchases, we will set the appAccountToken for you. The appAccountToken will **_not_** be set if:
> 
> 1. You are using something other than a valid UUID for the App User ID (RevenueCat iOS SDK v5.0+ only—previous versions will set the App User ID as the `appAccountToken`)
> 
> 2. We receive …
=> revises user identity section in apple server notifications doc

docs/web/web-billing/subscription-lifecycle.mdx
Web Billing subscriptions are renewed up to 1 hour before the period ends, not 24 hours.
=> Fix Web Billing renewal window

docs/getting-started/installation/android.mdx, docs/getting-started/installation/capacitor.mdx, docs/getting-started/installation/flutter.mdx, docs/getting-started/installation/ios.mdx, docs/getting-started/installation/kotlin-multiplatform.mdx, docs/getting-started/installation/reactnative.mdx, docs/getting-started/installation/roku.mdx, docs/getting-started/installation/web-sdk.mdx, docs/test-and-launch/debugging.mdx, docs/tools/customer-center/customer-center-flutter.mdx, docs/tools/customer-center/customer-center-integration-android.mdx, docs/tools/customer-center/customer-center-integration-ios.mdx, docs/tools/customer-center/customer-center-kmp.mdx, docs/tools/customer-center/customer-center-react-native.mdx, docs/tools/paywalls-v2/installation.mdx, docs/tools/paywalls/installation.mdx
We're preparing to release virtual currency beta SDKs for Android, and when they're released, these beta SDK versions will be the most recent versions. However, since they're betas, we don't want them appearing in all of our docs for everyone to install.
This PR adds a filter `filter=!*beta*` to all of our GitHub release imgshield images to ensure that we don't display any beta SDK versions as the latest stable version.
Documentation on the filter param can be found [here](https://shields.io/badges/git-hub-release).
=>  Don't include beta versions in imgshield images

docs/integrations/scheduled-data-exports.md
https://linear.app/revenuecat/issue/DENG-1166/twc-sdes-use-commas-instead-of-semicolons
=> etls use a comma delimiter

src/components/CustomerCenter/CustomerCenterSDKTable.tsx
Minimum required version for Customer Center in Flutter is 8.6.0 not 8.7.0. 
Minimum required version for Customer Center in React Native is 8.7.0 not 8.6.0.
=> Change Flutter version to 8.6.0 as required version

openapi-spec/api-v1.yaml
Our V1 API returns a store_transaction_id which wasn't documented. This adds it in and updates the examples with the property
- Update api-v1.yaml
=> add store_transaction_id property + update example

code_blocks/virtual-currency/vc-balance-sdk-flutter.dart, code_blocks/virtual-currency/vc-balance-sdk-react-native.ts, docs/offerings/virtual-currency.mdx
This PR introduces instructions for installing and using the virtual currency betas in React Native and Flutter.
It also makes a few minor tweaks to the native installation instructions.
=> Hybrid VC instructions

code_blocks/getting-started/installation/android_4.kts, code_blocks/getting-started/installation/android_5.kt, code_blocks/getting-started/installation/android_6.kts, docs/getting-started/installation/android.mdx
Improve the Android installation documentation by adding Kotlin code blocks. Since Google has announced Kotlin-first support for Android, most Android developers now use Kotlin as the default language—so including Kotlin snippets would better align with current development practices and benefit the majority of users.
=> Improve android installation docs by adding Kotlin code blocks

code_blocks/getting-started/configuring-sdk_6.js, code_blocks/getting-started/draft-quickstart_6.js, code_blocks/getting-started/getting-started-old_6.ts, code_blocks/getting-started/getting-started_6.ts
I realized we were still using `componentDidMount` for RN code snippets, which hasn't been best practice in more than 5 years! (Hooks were introduced in React 16.8 in February 2019, and became the de facto standard by early 2020).
=> Use hooks for RN code snippets

openapi-spec/api-v1.yaml
A potential customer looking to migrate to RC reached out to ask whether our https://api.revenuecat.com/v1/receipts endpoint supports JWSTransactions from StoreKit2.
I think this could be clarified in the future by adding just an explicit mention in the API docs. Maybe something like this?
:arrow_right: For iOS, the base64-encoded receipt file (or JWSTransaction for StoreKit2); for Android, the receipt token; for Amazon, the receipt; and for Stripe, the subscription ID or the Stripe Checkout Session ID.
=> Clarified JWSTransactions StoreKit2 support in API v1 doc

docs/integrations/third-party-integrations/customerio.mdx
The doc may not be clear enough about not using arbitrary values in `$customerioId`. You can't use it to create Person entries there, and setting it to an invalid format will cause Customer.io to reject the request with HTTP 400 errors.
=> Warn about invalid customerioId attribute values

docs/platform-resources/server-notifications/apple-server-notifications.mdx
Clarified how RevenueCat handles Apple Server-to-Server (S2S) notifications for a user that doesn't have any purchases. Previously, it wasn't clear that the notification would still be forwarded if a custom Apple Server Notification Forwarding URL was configured.
- Updated tip in the documentation to mention that S2S notifications are forwarded to the Apple Server Notification Forwarding URL, even if the user has no associated purchases in RevenueCat.
N/A
N/A
=> clarify Apple S2S handling and mention forwarding to custom URL

docs/web/web-billing/web-sdk.mdx
- Mention key purchase options available through PurchaseParams
- Remove now-duplicated Testing documentation (now in its own doc)
=> Add PurchaseParams options for web SDK

docs/getting-started/entitlements/ios-products.md
As the title says. This is reported by a customer. Seems like this is outdated in our docs. There's no "Agreements, Tax, and Banking" module in ASC (anymore).
"Agreements, Tax, and Banking" --> "Business" 
N/A
N/A
=> In ASC, the "Agreements, Tax, and Banking" module is now the "Business" module

docs/migrating-to-revenuecat/migrating-existing-subscriptions.mdx
Motivation / Description
There was a need to add clear expectations about data processing times for customers migrating to RevenueCat. Users were confused about why their imported purchase data wasn't immediately appearing in the dashboard, leading to support tickets and confusion during migration.
Changes introduced
Added a new "Data Processing Time" section to the migration documentation
Included specific timeframes for Customer Lists updates (several hours)
Included specific timeframes for Charts and Analytics updates (24 hours+)
Added clarification that individual customer data is still accessible during processing
Linear ticket (if any)
Additional comments
=> Add data processing time section to migration docs

docs/platform-resources/sdk-reference.mdx
We were pointing to a pretty old version of the flutter reference docs. This updates the link to use the latest.
=> fix: Use latest flutter version reference docs

docs/tools/customer-center/customer-center-integration-android.mdx
Customer Center was made available on Android in com.revenuecat.purchases:purchases-ui 8.12.2 and higher. However, our docs reference instantiating the Customer Center as an Activity, which is only available in 8.13.0 and higher.
This caused confusion for a customer in this ticket:
https://revenuecat.zendesk.com/agent/tickets/57242
=> ShowCustomerCenter version notice for Android

docs/tools/paywalls-v2/change-log.mdx, docs/tools/paywalls-v2/creating-paywalls/components.mdx, docs/web/web-billing/overview.mdx
This ruling is big news for IAP and RevenueCat.
- Adds sections to the Web Billing and Creating Paywalls docs related to the April 2025 IAP ruling against Apple
- Updates Paywalls-v2 change log to include Web Paywall as button destination.
=> Adds a section to the Web Billing docs related to the April 2025 IAP ruling against Apple

code_blocks/integrations/third-party-integrations/customerio_2.json, docs/customers/customer-attributes.mdx, docs/integrations/third-party-integrations/customerio.mdx
We will now pass the attribute value in `id` instead of `cio_id`
=> Use customerioId attribute for id

docs/web/faq.mdx, sidebars.js
Support's getting a lot of questions about external web payments with the recent ruling, need somewhere to hold context
- Adds a new FAQ for web-related changes, including a changelog
=> Add FAQ for web payments

docs/web/integrations/stripe.mdx
The Stripe Billing page doesn't refer the new ruling as Web Billing does. 
Updates:
- removed/reworded warning about App Store terms
- added court ruling info block about external payment options (same as Web Billing)
n/a
n/a
Web Billing as of today
-
Suggested update to Stripe Billing
-
=> docs: update App Store policy warning for US court ruling

docs/tools/paywalls-v2/creating-paywalls/components.mdx, docs/tools/paywalls-v2/creating-paywalls/web-paywall-button.mdx, docs/tools/paywalls-v2/creating-paywalls/web-purchase-button.mdx, docs/web/faq.mdx, sidebars.js
Expand surface area of the Web ~Paywall~ Purchase Button and additional FAQ details on web purchases
- Adds a new Web Purchase Button page
- New section in Components page
- List Paywalls v2 first and remove v1 recommended text
=> Add an explicit Web Purchase Button page

docs/web/web-billing/overview.mdx, docs/web/web-billing/web-purchase-links.mdx
Two renames were missed and also removing the "low code" mentions.
=> Missing Web Purchase Links renames

docusaurus.config.js
Rik mentioned the navbar 'Documentation' grouping isn't really clear that it's showing multiple sets of docs. This is a start at trying to make it more clear
- Change 'Documentation' to 'Categories'
=> Update "Documentation" menu -> "Categories"

docs/web/web-billing/overview.mdx
Web Billing (as per this [Slack thread](https://revenuecat.slack.com/archives/C05TUASTSG4/p1740160779944999?thread_ts=1739998199.712349&cid=C05TUASTSG4)) does not support translated emails - yet! This change is to let customer knows and have ourselves a place to reference this limitation.
Added a new bullet list item to reflect this
n/a
n/a
=> Added note from the Web Billing email translation limitation

docs/getting-started/displaying-products.mdx, docs/offerings/troubleshooting.mdx
Some customers are struggling to get offerings/products and it turns out this key is missing. Bringing it closer to them during the guide in order to try and be more explicit about it
Added a new block on the `docs/getting-started/displaying-products`
n/a
n/a
Before
-
After
-
Troubleshooting guide
-
=> Apple Shared Secret in guide setup

docs/web/integrations/paddle.mdx
Added a subsection to specify the Paddle API Keys premissions when defining it on Paddle's dashboard:
Collapsed:
Opened:
Check it here: https://dev-docs.revenuecat.com/pr-840/web/integrations/paddle
=> [PSP-183] Add Paddle API key permissions in the integration doc

code_blocks/getting-started/getting-started_6.ts, docs/getting-started/installation/expo.mdx, docs/getting-started/installation/reactnative.mdx, sidebars.js
Our Expo docs have been outdated for a while, this attempts to correct and provide much more specific guidance
- new Expo doc under the Installation section
- React Native installation docs link out now
=> Update Expo docs

sidebars.js, src/sidebars/sidebar-utils.js
The store FAQ pages all had the same "Amazon Appstore FAQs" title:
This is because they all had the same label in the sidebar and these pages are auto-generated by the sidebar. This fixes this by changing the titles of the FAQ pages to all be unique:
Now the pages have the correct titles:
~~Since I was already in the code, I also fixed the slug to say /docs/store-configuration/amazon/faqs instead of /docs/store-configuration/amazon/faqs-index. @codykerns was there a specific reason you were generating the FAQ pages on faqs-index?~~ nvm a bunch of links rely on generated indexes having -index so I undid this change.
Change labels of FAQ pages in sidebar to be unique
=> fix store faqs titles

docs/customers/customer-attributes.mdx
We were missing a $androidId and $tenjinId from our list of reserved customer attributes, so I added them in. Also removed a couple of attributes that were duplicated in the list.
=> Add missing reserved customer attributes

docs/known-store-issues/storekit.md, docs/known-store-issues/storekit/ios-18-2-purchase-sheet-may-fail-to-appear.md, sidebars.ts
- Document the StoreKit bug that causes purchase sheets to not appear on iOS 18.2.X
=> Document SK Bug with Purchase Sheets Not Appearing on iOS 18.2.X

docs/dashboard-and-metrics/display-currency.md
We support a couple extra currencies currently:
- RC App shows [this](https://github.com/RevenueCat/revenuecat-app/blob/12c10760abf24354b87fea1e5e8b5f19874a59ce/src/common/config.ts#L94)
- Khepri matches with [this](https://github.com/RevenueCat/khepri/blob/5ede4589145941065daf4c7f7e6d19fdafeede58/khepri/dal/domains/exchange_rates/model/daily_supported_exchange_rates.py#L16) 
Added
```
SEK: Swedish Krona
PLN: Polish Zloty
```
to the list
n/a
n/a
RC App in Date/Region settings
-
Current docs
-
As seen [here](https://www.revenuecat.com/docs/dashboard-and-metrics/display-currency#supported-currencies)
Updated docs
-
=> [Update] Added missing currencies to Dashboard displayed metrics

docs/web/web-billing/overview.mdx
Customer asked about mixed checkout (otp with subscriptions) and why their otp were not showing in RevenueCat.
[Slack here](https://revenuecat.slack.com/archives/C018CHK6A6R/p1749146951183789) and [ticket here](https://revenuecat.zendesk.com/agent/tickets/59394)
Added a new limitation entry
n/a
n/a
=> added limitation on mixed checkout sessions

docs/getting-started/installation/expo.mdx
Expands on the Expo docs to mention that react-native-purchases can now be installed on apps running in Expo Go and that they make use of the Preview API Mode
=> update expo docs to mention Preview API

docs/getting-started/installation/expo.mdx
The callout now links to https://www.revenuecat.com/blog/engineering/how-to-add-in-app-purchases-to-your-bolt-generated-expo-app/
=> Added Expo blog post callout

docs/dashboard-and-metrics/customer-lists.md
Added a section that documents the statuses available in customer lists and includes a note about how statuses filter only on customers who have made purchases.
=> List out statuses in customer lists

code_blocks/getting-started/installation/flutter_1.yaml, docs/getting-started/installation/flutter.mdx
- Added note in flutter_1.yaml to specify using purchases_flutter version 9.0.0-beta.3 for Flutter Web.
- Introduced a success callout in flutter.mdx announcing Flutter Web support in beta and linking to further information.
=> Add Flutter web callout in installation doc

code_blocks/tools/paywalls_cap_1.ts.txt, docs/tools/customer-center/customer-center-capacitor.mdx, docs/tools/customer-center/customer-center-installation.mdx, docs/tools/paywalls/displaying-paywalls.mdx, docs/tools/paywalls/installation.mdx, src/components/CustomerCenter/CustomerCenterSDKTable.tsx
We added Paywalls and Customer Center support in version 10.3.1 but we had not added it to the docs yet. This adds that.
=> Add Capacitor docs for Paywalls and Customer Center

code_blocks/known-issues/xcode-26-crash.swift, docs/known-store-issues/xcode-26.md, docs/known-store-issues/xcode-26/app-crash-urlsessionconfiguration.mdx, sidebars.ts
Apps compiled using Xcode 26, along with iOS 26 simulators, may crash when libraries initialize `URLSessionConfiguration`.  More information about the crash can be found [here](https://developer.apple.com/forums/thread/787365).
Because there's a suggested workaround for this issue, I created the following document for devs to refer to. 
- Changed the `Known Store Issues` categories into `Known Issues` to include Xcode 26 beta issues.
- Added Xcode 26 beta issues sub-category and pages.
- Added a code snippet on how to implement the workaround.
=> [Known Issues] - Xcode 26 URLSessionConfiguration Crash Workaround

docs/getting-started/quickstart.mdx
API Key location in the dashboard has changed. This PR updates the wording to be consistent with the new dashboard navigation. I used this page as a reference: https://www.revenuecat.com/docs/projects/authentication
=> Update Quickstart guide to reference new API key location

docs/web/web-billing/custom-metadata.mdx
As per this [Slack](https://revenuecat.slack.com/archives/C08H0L0RV09/p1750929387168319?thread_ts=1750770959.115989&cid=C08H0L0RV09) - we should mention the new event too on the custom metadata
Added the `NON_RENEWING_PURCHASE` section + tweaked the intro paragraph.
n/a
n/a
=> [Web Billing] Custom metadata added on NON_RENEWING_PURCHASE events

docs/web/web-billing/lifecycle-emails.mdx
Reverts RevenueCat/docs#961 since the FF for this feature is not open yet
=> Revert "Add documentation of new optional lifecycle emails for Web"

docs/welcome/overview.md, docusaurus.config.js, sidebars.ts, src/sidebars/sidebar-utils.ts
To start expanding playbooks, need to do a bit of maintenance to prepare for new categories and guides
- adds new monetization category with 'other resources' to link to non-playbook guides
- adds message to point to playbooks in the welcome page
=> [Playbooks] Add new category and links

docs/customers/customer-attributes.mdx
As far as I can tell, the reference of `accepted` being a possible value of `$attConsentStatus` is incorrect.
https://github.com/RevenueCat/purchases-ios/blob/main/Sources/Networking/CustomerAPI.swift#L102
https://developer.apple.com/documentation/apptrackingtransparency/attrackingmanager/authorizationstatus/authorized
Please review this change closely and ensure you agree with my interpretation.
=> Changed $attConsentStatus  'accepted' to 'authorized'

code_blocks/integrations/third-party-integrations/segment_5.json, code_blocks/integrations/third-party-integrations/segment_6.json, code_blocks/integrations/third-party-integrations/segment_8.json, code_blocks/integrations/third-party-integrations/segment_9.json
The [segment_event_dispatcher](https://github.com/RevenueCat/khepri/blob/main/khepri/events/dispatchers/segment_event_dispatcher.py#L204) does not use a `price` field. Instead, it uses `revenue` and `currency`.
`currency` is hard-coded to USD.
Resolves the discrepancy in affected events by renaming `price` to `revenue` and adding `"currency": "USD"` where it was missing.
=> Fix bug in some Segment event JSON examples

docs/web/guides/paddle-app-to-web.mdx
=> Add two new warnings about Paddle domain registration issue

docs/tools/paywalls/creating-paywalls/components.mdx
Tabs & the Switch component require going past RC's standard package identifiers and using custom ones, which I think need to be made more explicit in the instructions for how to use them.
=> Add instructions for using custom package IDs on Tabs & Switch

docs/tools/customer-center/customer-center-configuration.mdx
We've recently launched custom actions, and there's no mention in the docs.
- Add new path to documentation.
=> Mention custom actions on customer center docs

docs/known-store-issues/play-billing-library.md, docs/known-store-issues/play-billing-library/proxy-billing-activity-crash.mdx, sidebars.ts
Explains the reasons people are seeing this crash: https://github.com/RevenueCat/purchases-android/issues/2025.
=> Adds a known issue page on the `ProxyBillingActivity` crash.

code_blocks/virtual-currency/vc-balance-sdk-cordova.ts, docs/offerings/virtual-currency.mdx
This PR:
- Adds the Cordova SDK to the table of SDKs that support Virtual Currencies
- Adds a code sample showing how the virtual currency features can be used with the Cordova SDK
=> Add Cordova VC docs

docs/tools/targeting.md, sidebars.ts
Renaming the old 'offerings' category to product catalog makes targeting a bit out of place. should be it's own category
@dpannasch 
- Adds targeting to the top level categories
=> Add a top-level targeting category

code_blocks/integrations/webhooks/sample-events_1.json, code_blocks/integrations/webhooks/sample-events_10.json, code_blocks/integrations/webhooks/sample-events_11.json, code_blocks/integrations/webhooks/sample-events_12.json, code_blocks/integrations/webhooks/sample-events_2.json, code_blocks/integrations/webhooks/sample-events_3.json, code_blocks/integrations/webhooks/sample-events_5.json, code_blocks/integrations/webhooks/sample-events_6.json, code_blocks/integrations/webhooks/sample-events_7.json, code_blocks/integrations/webhooks/sample-events_9.json
A bunch of our sample webhooks were missing `tax_percentage` and `commission_percentage` fields (customer pointed this out); this fixes that.
=> Add tax_percentage and commission_percentage to webhook samples where it was missing

docs/projects/collaborators.md
The ability to create app/web configs was removed by mistake on the dashboard. We're reverting to the previous behavior.
=> Re-allow developer collaborators to create app configs

docs/getting-started/installation/expo.mdx
`npm install -g expo` installs `expo` globally and is invalid. It's hard to predict what consequences installing `expo` globally will have.
These instructions are also out-of-order, which may be accidental. Installing the `expo-dev-client` comes too early since it's in a section before this proposes to create an app. The instructions for a Development Build are already at the top.
- Remove installation section
It's a little unclear to me what the intention or order was meant to be. It's likely that this may need some refinement but the main motivation was to remove the global `expo` installation instruction.
=> Update Expo installation instructions

docs/dashboard-and-metrics/charts/paywall-abandonment-chart.md, docs/dashboard-and-metrics/charts/paywall-conversion-chart.md, docs/dashboard-and-metrics/charts/paywall-encounter-chart.md, docs/dashboard-and-metrics/charts/paywall-ltv-chart.md
Docs About paywall encounter chart which shows what % of new customers encounter a paywall in X days. The chart is (together with other paywall charts) hidden for now since it is behind a FF.
Also,
info section to indicate all paywall charts requires RC Paywall implementation
=> Paywall Encounter Chart

src/theme/DocSidebarItem/Category/index.tsx
When viewing a docs page from a direct link, in some cases categories weren't auto expanding to show where you were in the sidebar
- fixes the active page checker to expand categories
=> Fix categories not auto expanding when visited directly

.github/workflows/stale.yml
Let's automate reminding authors of PRs that need to be merged or closed.
=> ci: add stale issue/pr workflow

docs/getting-started/installation/android.mdx, docs/getting-started/restoring-purchases.mdx
This adds some information to the RevenueCat installation docs about how to setup the app's backup system to make sure to backup RevenueCat data correctly, to minimize lost purchases that needs to be restored (when possible), or that may be lost on the migration to BC8
=> Add android backup docs

openapi-spec/api-v1.yaml
It's super confusing which ID is required for the Google Play defer endpoint. This clarifies that the Subscription Id in the product catalog -> product is what we need.
=> Clarified which product ID is required for the Google defer endpoint

openapi-spec/api-v1.yaml
It looks like in this [PR](https://github.com/RevenueCat/docs/pull/1132) I just made, the **product** in `RevenueCat's Product catalog -> <product> -> Subscription Id.` was stripped:
Hopefully this renders ok
=> Fix ugly formatting

code_blocks/integrations/scheduled-data-exports_14.pgsql
teeny tiny typo in the query where the comma was inside of the quotes and missing ANDs in the joins
=> fix tiny typo in subscription retention query

docusaurus.config.js, package.json, src/plugins/markdown-alternates/frontMatter.js, src/plugins/markdown-alternates/index.js, src/plugins/markdown-alternates/mdxToMarkdown.js, static/llms.txt
Make it easier for LLMs to consume our docs content. 
- vibe coded a docusaurus plugin which generates markdown twins for the html content in docs. 
- added a link tag in html head pointing towards the markdown files for discoverability
- added information about markdown content to llms.txt
TODO: 
we still need to configure two things:
- add a Link HTTP header pointing to the markdown file when an html file is requested
- add some well known AI crawlers/agents User Agents to receive the markdown files by default.
both of the TODOs above require some CloudFront config beyond what we can do with the Azure deploy script.
=> Markdown docs for LLMs

code_blocks/getting-started/installation/kmp_1.toml, code_blocks/getting-started/installation/kmp_2.kts
We have deprecated the `:purchases-kmp-datetime` module in https://github.com/RevenueCat/purchases-kmp/pull/514, so we should no longer direct people to use it. Its functionality has been absorbed into `:purchases-kmp-core`.
=> Removes mentions of `:purchases-kmp-datetime`.

docusaurus.config.js
Disable swcHtmlMinimizer to prevent layout issues.
=> Disable swcHtmlMinimizer in configuration

docs/dashboard-and-metrics/charts/real-time-charts.md
=> Real-time Charts: Cohort Explorer methodology update
