code_blocks/integrations/scheduled-data-exports_2.pgsql
code_blocks/integrations/scheduled-data-exports_4.pgsql
code_blocks/integrations/scheduled-data-exports_9.pgsql

just fixing a syntax error in some SDE queries

Fix extra parens in SDE queries

---

docs/welcome/authentication.md

Adding suggestion for secret keys rotations. We had a [hackerone report](https://revenuecat.slack.com/archives/C06R7Q4RE7Q/p1735645990904669) for this too.

Add suggestion for frequent rotation of secret keys

---

docs/web/revenuecat-billing/localization.mdx

More prominent beta translation warning for RC Billing

---

openapi-spec/api-v2-beta.yaml
openapi-spec/api-v2.yaml

Auto-generated PR to update API v2 OpenAPI specs

Update API v2 OpenAPI Specifications

---

docs/web/revenuecat-billing.mdx
docs/web/revenuecat-billing/product-setup.md

Add documentation for Web Billing accelerated sandbox.

Web Billing Accelerated Sandbox

---

docs/web/revenuecat-billing.mdx
docs/web/revenuecat-billing/product-setup.md

Revert "Web Billing Accelerated Sandbox"

---

docs/dashboard-and-metrics/charts/customer-center-survey-responses-chart.md

We started sending the event in version 5.14.0

Add minimum SDK to customer center chart

---

docs/web/revenuecat-billing/payment-methods.mdx

More specific details around Apple payment domains and testing

---

docs/customers/user-ids.mdx

There seems to be a lot of confusion on what id comes in the webhooks data. I hope this will clear things.

Specify what id they will get in their webhooks

---

docs/web/web-billing/subscription-lifecycle.mdx

Add the "uncancellation" flow to the Web Billing subscription lifecycle docs

Add uncancellation to RCB lifecycle

---

docs/tools/paywalls-v2/creating-paywalls/components.mdx

Who among us has not swapped a parentheses and a bracket am I right?

Paywalls v2: Fix broken link

---

code_blocks/_projects/web-billing/package.json
code_blocks/_projects/web-billing/web-billing-doc-snippets.test.ts
code_blocks/_projects/web-billing/web-billing-doc-snippets.ts
docs/getting-started/displaying-products.mdx
docs/web/web-billing.mdx

Bump `purchases-js` dependency for code snippets

Update purchase-js SDK

---

code_blocks/getting-started/configuring-sdk_5.js

code was deprecated, changed it to the correct code

Update flutter deprecated logging

---

docs/tools/paywalls-v2.mdx

As the title says. ~~Still a draft until the SDKs are actually released and the versions are final.~~

Includes newly supported SDKs in Paywalls V2 docs.

---

docs/tools/paywalls-v2/displaying-paywalls.mdx

Clarify details for implementing on Android, React Native, Flutter, and KMP.

Remove close button details

---

code_blocks/getting-started/installation/roku-subscriber-info.brs

Fix Roku method name

---

docusaurus.config.js

Instead of defaulting to light mode, default to the system preference.
Ref COFE-362

Support system dark mode

---

docs/web/web-billing/overview.mdx
docs/web/web-billing/web-paywall-links.mdx
docs/web/web-billing/web-sdk.mdx

Remove remaining 3 beta warnings for web

---

docs/offerings/troubleshooting.mdx

Added this step, as we've found it can cause empty offerings

Added iOS Apple Developer Membership Program check to empty offerings wizard

---

docs/integrations/attribution/facebook-ads.mdx

We are rolling out the integration with the Conversions API. Adding some details on how to set it up.

Documenting meta conversions API

---

docs/tools/paywalls-v2/change-log.mdx
sidebars.js

Publish the changes so the people know what's up

Paywalls v2 Change Log

---

docs/tools/paywalls-v2/change-log.mdx

Paywalls v2 change log updates

---

code_blocks/virtual-currency/balance-response.json
code_blocks/virtual-currency/idempotency-key.curl
code_blocks/virtual-currency/transaction-response.json
docs/offerings/virtual-currency.mdx

Update code blocks + add Tips & Hints for VC beta

---

code_blocks/tools/customer-center-events-android-base.kt
code_blocks/tools/customer-center-events-android-global.kt
code_blocks/tools/customer-center-events-android-local.kt
code_blocks/tools/customer-center-events-react-native.tsx
code_blocks/tools/customer-center-usage-2.kt
code_blocks/tools/customer-center-usage-3.kt
docs/tools/customer-center/customer-center-integration-android.mdx
docs/tools/customer-center/customer-center-integration-ios.mdx
docs/tools/customer-center/customer-center-promo-offers-google.mdx
docs/tools/customer-center/customer-center-react-native.mdx

- Added callbacks to React Native

Customer center various improvements

---

code_blocks/virtual-currency/firebase-balance.json
docs/offerings/virtual-currency.mdx

Adds details about Firebase Extensions for virtual currency

Add details about firebase extensions

---

docs/revenuecat-support/general-troubleshooting.mdx

This adds a section we can point users to in order to understand and fix the issue Google introduced in Billing client 7.1.+

Add note about crashes in old android devices due to Billing client issue

---

docs/revenuecat-support/general-troubleshooting.mdx

Fixes lefover from #713.  I copied this message directly from the SDK before it was updated. This fixes that

Fix leftover TODO-LINK

---

docs/offerings/virtual-currency.mdx

This PR includes the minimum and maximum balance that a user may have for a single virtual currency.

Document VC Max Balance

---

code_blocks/customers/customer-info_3.kt
code_blocks/getting-started/getting-started-old_29.kt
code_blocks/getting-started/getting-started_29.kt
code_blocks/subscription-guidance/managing-subscriptions_4.kt

Use accurate `getCustomerInfoWith` API for Kotlin.

Use accurate getCustomerInfoWith API for Kotlin

---

docs/tools/paywalls-v2/creating-paywalls/components.mdx

Components page fixes

---

docs/tools/paywalls-v2/creating-paywalls/components.mdx

Added them to one table, forgot them in another. I should turn this into a code snippet in the future.

Paywalls v2: One more fix for the new components

---

package.json
yarn.lock

Resolves https://github.com/RevenueCat/docs/security/dependabot/7

chore: regen lockfile, force redoc upgrade

---

docs/offerings/virtual-currency.mdx

Add explicit rate limits to virtual currency

---

docs/tools/paywalls-v2.mdx
docs/tools/paywalls/installation.mdx

Add explicit paywalls incompatibility for SDKs

---

docs/web/web-billing/custom-metadata.mdx

Expanding web custom metadata support documentation

---

docs/offerings/virtual-currency.mdx

Swap VC reading and spending sections

---

docs/tools/paywalls-v2/change-log.mdx
docs/tools/paywalls-v2/creating-paywalls/variables.mdx

Pv2: Updates to the change log (Apr 14)

---

code_blocks/getting-started/configuring-sdk_10_kmp.kts
code_blocks/getting-started/getting-started_52.kt
code_blocks/getting-started/installation/kmp_7.kts
docs/getting-started/quickstart.mdx

This was reported by a developer. Some of the code snippets we provide would result in unintended errors in the IDE when pasted. 
Kotlin Multiplatform code snippet fixes only. 
N/A
N/A

Fixes some purchases-kmp code snippets

---

code_blocks/integrations/webhooks/sample-event-invoice-issuance.json
code_blocks/integrations/webhooks/sample-event-refund-reversed.json
code_blocks/integrations/webhooks/sample-event-temporary-entitlement-grant.json
docs/integrations/webhooks/sample-events.mdx

Add missing sample webhook events

---

openapi-spec/api-v1.yaml

Add Roku and Paddle to  API V1 documentation

---

docs/tools/paywalls-v2.mdx

https://revenuecat.slack.com/archives/C07H5S8CFL3/p1746591008720869

Reduce the warning direness on Paywalls v2

---

docs/web/web-billing/redemption-links.mdx

Typos aren't great.
Fixes a typo when referencing SwiftUI.
NA
NA

Fixes a typo when referencing SwiftUI.

---

docs/web/faq.mdx

Clarifying questions about whether IAP can be removed entirely
- Adds a new question to the web FAQ

Add clarity on IAP and web payments

---

docs/web/faq.mdx

We shipped some improvements to the Web Purchase Button

Add improvements to web changelog

---

docs/web/faq.mdx

Slightly restructure web FAQs

---

docs/tools/targeting.md

Targeting: Fix incorrect SDK version support reference

---

docs/web/web-billing/overview.mdx

Explained why we cannot support purchases in India at the moment.

---

openapi-spec/api-v1.yaml
openapi-spec/external-purchases-api.yaml

Add base URL to the API docs for v1 and external purchases API. v2 will have do be done from khepri.

Add base URL to API docs

---

docs/offerings/virtual-currency.mdx

[Virtual Currencies] Add note about invalidating customer info cache when balance changes

---

code_blocks/_projects/web-billing/package.json
code_blocks/customers/subscriber-attributes_26.js
code_blocks/customers/subscriber-attributes_27.js
code_blocks/customers/subscriber-attributes_28.js
docs/customers/customer-attributes.mdx

This PR adds new JavaScript code snippets for setting subscriber attributes specifically for the Web Billing. It also updates an existing library to a newer version.
- Updated `@revenuecat/purchases-js` from version `^0.16.0` to `^1.4.0`.
- Added new code snippets for subscriber attributes for Web Billing
- Updated the documentation to include the new code snippets for better guidance.

Update dependencies and add new subscriber attributes examples

---

docs/integrations/attribution/tenjin.mdx

Update Tenjin helper method availability

---

docs/web/web-billing/tax.mdx

Update copy about beta access to tax support feature

---

docs/tools/experiments-v1/experiments-results-v1.md

Add paywall viewers to experiments results

---

docs/dashboard-and-metrics/charts/realized-ltv-per-customer-chart.md
docs/known-store-issues/storekit.md
docs/known-store-issues/storekit/ios-18-purchase-fails-due-to-failed-storekitdaemon-connection.md
sidebars.ts

- Documents purchases May Fail Due to StoreKit Daemon Connection Issue

Document Purchases May Fail Due to StoreKit Daemon Connection Issue

---

docs/web/web-billing/tax.mdx

remove beta information for Stripe Tax integration

---

docs/subscription-guidance/subscription-offers/google-play-offers.md

Noticed some **bolds** not bolding.
Fixed the spacing
n/a
n/a
1 Redeem Code
-
<image src="https://github.com/user-attachments/assets/7c7864d9-165b-4d53-bd99-f64577eed6dc" width=500/>
<image src="https://github.com/user-attachments/assets/d2ad8fd2-be79-4ba4-8034-75b509527db5" width=500/>
----------------------------------------------------------------------------------------------------------------------------
2 Table bits
-
<image src="https://github.com/user-attachments/assets/4c0d4efe-a62e-4b33-a316-533f307c2ccd" width=500/>
<image src="https://github.com/user-attachments/assets/e03cc4b9-81b2-4275-82b8-94e5590d857d" width=500/>
----------------------------------------------------------------------------------------------------------------------------
3 Promo codes
-
<image …

fixed bold spacing

---

docs/tools/paywalls.mdx

Paywalls v2: Update video for GA

---

docs/dashboard-and-metrics/charts/customer-center-survey-responses-chart.md

Tiny PR - add a link from the customer center survey responses chart to the configuration documentation

Add link from customer survey response chart to the configuration instructions

---

docs/dashboard-and-metrics/charts/real-time-charts.md

Updates to real-time charts docs

---

docs/web/web-billing/custom-metadata.mdx
docs/web/web-billing/overview.mdx

Reverts RevenueCat/docs#932
Support was added today

Revert "added limitations on metadata web billing"

---

docs/web/web-billing/lifecycle-emails.mdx

Add info about new california subscriptions law

---

docs/tools/customer-center/customer-center-promo-offers-apple.mdx
docs/tools/customer-center/customer-center-promo-offers-google.mdx

Added a little note about promotional offers

Little note on cross product offers in Customer Center

---

docs/platform-resources/server-notifications/apple-server-notifications.mdx

A customer created a ticket because they didn't understand what using Version 2 or Version 1 meant. 
Updated the copy so that it is clearer what we mean when we say customers can use one version or the other

[Apple Server to Server Notifications] - Small update

---

docs/web/integrations/paddle.mdx

Noticed `PAddle` instead of `Paddle`
A letter change
n/a
n/a

PAddle -> Paddle

---

docs/integrations/attribution/adjust.mdx

Update Testing Console help article url for Adjust

Update Testing Console help article url for Adjust

---

docs/dashboard-and-metrics/charts/real-time-charts.md

Real-time Charts Updates (July 1st)

---

src/theme/DocItem/index.tsx

Add meta tag for algolia if hidden page

---

docs/welcome/overview.md
src/theme/Footer/index.tsx
static/llms.txt
static/robots.txt

Continuing to improve AI support. Doesn't yet expose raw markdown, but adds llms.txt

Add support for llms.txt

---

docs/web/web-billing/lifecycle-emails.mdx

Restore "Add documentation of new optional lifecycle emails for Web"

---

code_blocks/virtual-currency/cached-virtual-currencies.swift
docs/offerings/virtual-currency.mdx

This PR updates the docs to include information related to the upcoming iOS VC native SDK release.

Update docs for iOS VC release

---

docs/tools/paywalls/change-log.mdx
docs/tools/paywalls/creating-paywalls/web-purchase-button.mdx

Catching up the change log from the last month

Paywalls updates (July 7th)

---

docs/tools/customer-center.mdx
src/theme/DocItem/index.tsx

Adds new header values for the algolia crawler

Support hidden and prioritized search pages

---

sidebars.ts

Update Charts sidebars to match dashboard

---

docs/platform-resources/apple-platform-resources/app-store-small-business-program.md

Fixed reference to outdated dashboard settings

---

code_blocks/getting-started/installation/android_1.groovy
code_blocks/getting-started/installation/android_3.groovy
code_blocks/getting-started/installation/android_4.kts
code_blocks/getting-started/installation/android_6.kts
code_blocks/getting-started/making-purchases_5.js.txt
code_blocks/getting-started/making-purchases_8.cs
code_blocks/subscription-guidance/subscription-offers/ios-winback-offers-purchase-winback-offer-flutter.dart
code_blocks/test-and-launch/debugging_13.groovy
code_blocks/web/web-billing/redemption_flutter.dart

This updates the docs with some breaking changes caused by the latest majors, specially in Flutter and Unity, where the purchase methods now return a PurchaseResult object, instead of a CustomerInfo.

Update docs after new majors

---

docs/offerings/virtual-currency.mdx

This PR adds a table to the virtual currency docs that shows which SDK versions are required to fetch virtual currency balances.

[Virtual Currencies]: Add VC SDK Versions Support Table

---

docs/dashboard-and-metrics/charts/customer-center-survey-responses-chart.mdx

Add table of SDK versions to customer-center-survey-responses-chart

---

code_blocks/virtual-currency/vc-balance-sdk-android.java
code_blocks/virtual-currency/vc-balance-sdk-android.kt
code_blocks/virtual-currency/vc-balance-sdk-ios.swift
code_blocks/virtual-currency/vc-balance-sdk-react-native.ts
docs/offerings/virtual-currency.mdx

This PR:
- Adds the React Native SDK to the table of SDKs that support Virtual Currencies
- Adds a code sample showing how the virtual currency features can be used with the React Native SDK
- Adds a note mentioning that developers should call `invalidateVirtualCurrencies()` after a purchase completes successfully.
- Standardizes the comments in the code samples

Add RN VC Docs

---

docs/offerings/virtual-currency.mdx

Updating VC docs for public beta

---

docs/welcome/set-up-revenuecat/security.md
docusaurus.config.js

Add callout for exposed passwords check

add callout for exposed password security

---

src/components/AIToolsContainer/AIToolsContainer.tsx

The Claude link has the wrong path
- fix Claude link

Fix Claude ai url 

---

docs/dashboard-and-metrics/charts/real-time-charts.md

Real-time Charts Docs (Aug 1st update)

---

code_blocks/tools/customer-center-custom-actions-android.kt
code_blocks/tools/customer-center-custom-actions-ios.swift
docs/tools/customer-center/customer-center-integration-android.mdx
docs/tools/customer-center/customer-center-integration-ios.mdx

We want to show how this new feature is used
Add dedicated section with code example

Add custom actions section to customer center 

---

docs/web/guides/paddle-app-to-web.mdx

Clarification around paddle payment domain approval on production

---

docs/offerings/virtual-currency.mdx

Adds a small callout to contact support

Virtual currency rate limit blurb

---

sidebars.ts

add blog post to vc faq

---

docs/web/web-billing/product-setup.md

rename web article title

---

docs/web/web-billing/product-setup.md

* Remove beta disclaimer for Web Billing introductory offers. 
* Fix accelerated sandbox info

Remove private beta for intro offers

---

docs/web/web-billing/subscription-lifecycle.mdx

include intro offers description in subscription lifecycle doc

---

docs/integrations/customer-support/zendesk.mdx

We got some feedback about some steps in the Zendesk setup.
- Clarifies v2 api
- Clarifies permission
(cc @ekurutepe)

Zendesk clarifications

---

docs/service-credentials/itunesconnect-app-specific-shared-secret/in-app-purchase-key-configuration.mdx

Add sdk versions for in app purchase keys

---

docs/web/web-billing/overview.mdx

Just noticed a small typo while researching web payments.
Swapped two letters. 🙂
N/A

Fix small typo

---

docs/platform-resources/google-platform-resources/google-play-pass.md

Document PlayPass transactions having price 0.

---

code_blocks/getting-started/installation/configuring-roku_2.brs
code_blocks/getting-started/installation/roku-tying-together.brs

[Roku] update configure block

---

code_blocks/getting-started/draft-quickstart_48.js.txt
code_blocks/getting-started/draft-quickstart_49.js.txt
code_blocks/getting-started/getting-started-old_48.js.txt
code_blocks/getting-started/getting-started_48.js.txt
docs/getting-started/installation/flutter.mdx

Update old references to Flutter's PurchaserInfo

---

code_blocks/tools/paywalls_preferred_locale_1.swift
code_blocks/tools/paywalls_preferred_locale_2.kt
code_blocks/tools/paywalls_preferred_locale_3.ts.txt
docs/tools/paywalls/change-log.mdx
docs/tools/paywalls/displaying-paywalls.mdx

Adding some paywalls September changelog
Things

Paywalls September changelog

---

docs/offerings/virtual-currency/expiring-currencies.md
sidebars.ts

This adds additional details about product changes for expiring currencies. It also adds the doc to the sidebar, as well as unhiding the documentation.
Do not merge until functionality is enabled

Product change for expiring currencies

---

.github/workflows/stale.yml

It wasn't closing things after marking them as stale.

ci: fix stale workflow permissions
